name: Format Code

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'


jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Format code with Prettier
        run: npx prettier --check "src/**/*.{ts,tsx,js,jsx}"
